menu:
- {name: 'Home', url: '/index'}
- {name: 'Publications', url: '/publications'}
# - {name: 'courses', url: '/courses'}
# - {name: 'Activities', url: '/cv'}
- {name: 'Contact', url: '/contact'}

people:
- {name: 'Primary Investigator', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/primary-investigator.jpg', url: 'primary-investigator'}
- {name: 'Lab Technician', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/lab-technician.jpg', url: 'lab-technician'}
- {name: 'Graduate Student', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/graduate-student.jpg', url: 'graduate-student'}

courses:
- {name: 'Vector Calculus', url: 'vector-calculus'}
- {name: 'Quantum Mechanics', url: 'quantum-mechanics'}
- {name: 'Stellar Structures', url: 'stellar-structures'}

social:
- {icon: 'github', link: 'https://github.com/JackyXiao98'}
# - {icon: 'twitter', link: 'https://twitter.com/paululele'}
# - {icon: 'instagram', link: 'https://instagram.com/paululele'}
# - {icon: 'scholar', link: 'https://scholar.google.com/citations?user=eCBNsH0AAAAJ&hl=en'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/yingtai-xiao-2b795515a/'}

contacts:
- {name: 'Yingtai Xiao', title: 'Research Scientist', department: 'Privacy Innovation Lab', institution: 'TikTok Inc.', institution_address: 'San Jose, CA, USA', phone: 'Hidden', email: 'yingtai.xiao1 at bytedance.com', image: 'assets/img/tiktok.jpg'}
